export enum EAuth {
    SIGN_IN = "SIGN_IN",
    SIGN_OUT = "SIGN_OUT",
    RESTORE_TOKEN = "RESTORE_TOKEN",
    RESTORE_TOKEN_GOOGLE = "RESTORE_TOKEN_GOOGLE",
    AUTH_FAIL = "AUTH_FAIL",
    AUTH_WARN = "AUTH_WARN",

}

export enum EDemoHello {
    DEMO_HELLO = "DEMO_HELLO",
    DEMO_HELLO2 = "DEMO_HELLO2",
}

export enum EDemoThunk {
    DEMO_THUNK_SUCCESS = "DEMO_THUNK_SUCCESS",
    DEMO_THUNK_FAILED = "DEMO_THUNK_FAILED",
}


